var CadesConstants = {
    STORE: "CAdESCOM.Store",
    SIGNER: "CAdESCOM.CPSigner",
    SIGNED_DATA: "CAdESCOM.CadesSignedData",
    userStore: cadesplugin.CAPICOM_CURRENT_USER_STORE,
    MY_STORE: cadesplugin.CAPICOM_MY_STORE,
    STORE_MAXIMUM_ALLOWED: cadesplugin.CAPICOM_STORE_OPEN_MAXIMUM_ALLOWED,
    FIND_SUBJECT_NAME: cadesplugin.CAPICOM_CERTIFICATE_FIND_SUBJECT_NAME,
    FIND_SHA1_HASH: cadesplugin.CAPICOM_CERTIFICATE_FIND_SHA1_HASH,
    INCLUDE_WHOLE_CHAIN: cadesplugin.CAPICOM_CERTIFICATE_INCLUDE_WHOLE_CHAIN,
    BASE_64_TO_BINARY: cadesplugin.CADESCOM_BASE64_TO_BINARY,
    CADES_BES: cadesplugin.CADESCOM_CADES_BES,
    CADES_X_LONG_TYPE_1: cadesplugin.CADESCOM_CADES_X_LONG_TYPE_1
};